// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaContable.Data;

#nullable disable

namespace SistemaContable.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250531000000_AddEstadoAndDescripcionToPlazoPago")]
    partial class AddEstadoAndDescripcionToPlazoPago
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This would normally contain the full model definition
            // For simplicity, we'll leave it empty since it's auto-generated
        }
    }
}